### PR TITLE
Add FitbitHRtoWS Support

### PR DESCRIPTION
**Pull request by 200Tigersbloxed**
First, let me start by saying this is the first ever PR I've ever done, so figuring out how to get to the point of 3 Files Changed took me hours.

Now let me get into the details of this PR. This PR adds full support for FitbitHRtoWS. If you've seen my previous fork, it was done in a very sloppy manner, hence why I didn't PR it. I made a new fork, starting over from scratch, and now I have made it so it integrates with your current system. I have already tested the changes in my own build, and it seemed to work perfectly fine. I haven't checked for console flooding, but that shouldn't be a problem. Attached below is my build, so if you'd like to test anything, please feel free to do so.

[HRCounter.zip](https://github.com/qe201020335/HRCounter/files/6796486/HRCounter.zip)

As for file changes:

+ `Config\PluginConfig.cs`
  + Added `FitbitWebSocket` (string)
    + Specifies the WebSocket URL that the client's FitbitHRtoWS Socket runs on.
    + This is just a normal String
  + Added `FitbitHRtoWS` property for `DataSource`
    + This is just the `DataSource` identifier.
    + Note that this will need to be Caps-Sensitive, since the switch-case in the `HRCounter.cs` doesn't ToLower() the string.
+ `Data\FitbitHRtoWS.cs`
  + The Data manager for FitbitHRtoWS
  + Derivative of `BpmDownloader`
+ `HRCounter.cs`
  + Added `"FitbitHRtoWS"` to switch-case
    + This is just for setting the `BpmDownloader` to `FitbitHRtoWS`

Some final notes:

I plan to re-write FitbitHRtoWS, but I plan to have backwards-compatibility for it. Once re-written, I'll probably try and get the FitbitHRtoWS app on the Fitbit Store, and maybe even have it call more data than just heartrate.

### CODE REVIEW

**Comment by 200Tigersbloxed** [comment]
Found an issue where if the websocket isn't connected, game will freeze and crash. Making changes to fix

**Comment by 200Tigersbloxed** [comment]
Fixed! The `Start()` of the FitbitHRtoWS class will now make sure that the connection to the WebSocket is alive before starting the updating loop. There's also a "KillSwitch" build in place that will immediately stop the loop as soon as the Connection to the WebSocket is closed.

Here's the build: 
[HRCounter-1.2.1-bs1.16.2-102ce7b.zip](https://github.com/qe201020335/HRCounter/files/6809216/HRCounter-1.2.1-bs1.16.2-102ce7b.zip)

**Comment by qe201020335** [comment]
I think you forget to commit the changes in `HRCounter.csproj` file. The newly added `FitbitHRtoWS.cs` is not included in the project.

**Comment by 200Tigersbloxed** [comment]
Yes I did indeed, let me do that real quick.

**Comment by 200Tigersbloxed** [comment]
All done! Should be good to go! Let me know if there's anything else!

**Comment by qe201020335** [comment]
Do you want me to make a release about the FitbitHRtoWS support or I should wait? since you mentioned your plan to re-write it and release on the Fitbit Store. 

Some personal opinion, 
I think setting up a dedicated ws server (+ node.js environment) is a bit too much for a normal user, so it will be really great if you can release an app on Fitbit Store.

**Comment by 200Tigersbloxed** [comment]
I'll try and get the current app on the store. It's stable enough for it to be user friendly. I'll need to make the WebSocket server into an executable though so it can be easier to setup, along with a server config.

The rewrite will be farther down the road, I plan to get *all* data from the Fitbit. I'll get on this and try and finish this ASAP.

It's up to you if you want to announce the release, but since there's no other update than FitbitHRtoWS support, than I suppose we could hold it off until this is finished.

**Comment by 200Tigersbloxed** [comment]
Just finished the server part to make it more user-friendly. Used pkg to bundle the code into a single executable for windows and linux. Config now runs off of a `config.json` file that'll be in the same directory.

Tried connected my watch to the developer bridge, and I got rate limited. I have to wait an hour before I can start working on getting the app up, which will be VERY difficult, but so is everything else with the fitbit sdk. (150 requests per hour, just in case you were wondering) **I hate the Fitbit SDK.** kek

**Comment by 200Tigersbloxed** [comment]
I've finished the new update (finally). I had to hurdle through multiple obstacles that Fibit throws at you, which I won't get into because that list is long, but it's now more user-friendlier than ever to setup! Tested it and it works just like before!

You can read more about it here:
+ https://github.com/200Tigersbloxed/FitbitHRtoWS/releases/tag/v1.4.0
+ https://github.com/200Tigersbloxed/FitbitHRtoWS/wiki/Setup

You're good to announce the release of FitbitHRtoWS now as long as this looks good!

**Comment by qe201020335** [comment]
Thanks a lot for your update!

**Pull request merged**
